//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OS0820GSH\\LOVEGIVE;Initial Catalog=QUANLYKHACHSANKIMANH;Integrated Se" +
            "curity=True")]
        public string QUANLYKHACHSANKIMANHConnectionString {
            get {
                return ((string)(this["QUANLYKHACHSANKIMANHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOANGUYEN-PC\\SQLEXPRESS;Initial Catalog=QUAN_LY_NHA_HANG_KHACH_SAN_HO" +
            "AN_HIEP;Integrated Security=True")]
        public string QUAN_LY_NHA_HANG_KHACH_SAN_HOAN_HIEPConnectionString {
            get {
                return ((string)(this["QUAN_LY_NHA_HANG_KHACH_SAN_HOAN_HIEPConnectionString"]));
            }
        }
    }
}
